spring:
  application:
    name: cubeai

  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile
              - phone
              - email

springdoc:
  packages-to-scan: com.cubeai
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method

jwt:
  token:
    secret-key:
    expiration:
      access: 3600000
      refresh: 604800000
    redirect-url: http://localhost:3000
    cookie-domain: